# Generated by Django 5.1.1 on 2024-10-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Revenus additionnels de l'utilisateur.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Revenu annuel de l'utilisateur.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deductions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total des déductions fiscales.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_dependents',
            field=models.IntegerField(blank=True, help_text='Nombre de personnes à charge.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_credits',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant des crédits d'impôt.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_residence_country',
            field=models.CharField(blank=True, choices=[('fr', 'France'), ('be', 'Belgique'), ('ca', 'Canada')], help_text='Pays de résidence fiscale.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_status',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married_joint', 'Marié - Déclaration conjointe')], help_text="Statut fiscal de l'utilisateur.", max_length=20, null=True),
        ),
    ]
